logger:
  mode: dev
  log-format: json
  log-level: debug
  datetime-format: "2006-01-02 15:04:05"
  use-timestamp: false
  include-caller-method: true

storage:
  postgres:
    connection-string: "host=dumbo.db.elephantsql.com user=wjvawxmp dbname=wjvawxmp password=kqxLJRwAp1OccCF2_pcwHE6DVbG76v_6 sslmode=disable"
    # connection-string: "host=localhost port=5432 user=postgres dbname=dvdrental password=postgres sslmode=disable"
    conn-max-idle-num: 3
    conn-max-open-num: 3
    driver: pgx
    dialect: postgres
    max-retries: 5
    retry-delay: 100s
    conn-max-lifetime: 100s
    query-timeout: 100s
    auto-migrate: true
    migration-directory: "dbschema/migrations"
    migration-direction: "up"
  redis:
    connection-address: "localhost:6379"
    db: 0
    pass: ""
    max-retries: 5
    retry-delay: 10s
    query-timeout: 10s

delivery:
  http-server:
    log-requests: true
    listen-address: 0.0.0.0:40001
    read-timeout: 100s
    write-timeout: 100s
    body-size-limit: 10128
    graceful-timeout: 60

extra:
  redis-cache:
    time-live: 30s
  local-cache:
    time-live: 15s
    number-of-records: 100
